name = "RomeoApp"
uuid = "6ec04266-ba88-41a1-94ab-4aa3de757d7e"
authors = ["Korbinian Eckstein", "High Field MR Centre", "Medical University Vienna"]
version = "0.4.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
ROMEO = "1ea8258b-a15d-4adb-ad20-01632f467a84"

[compat]
ArgParse = "1"
MriResearchTools = "0.4, 0.5"
ROMEO = "0.2.4"
julia = "1.5"
